version: "3"
services:
    app:
      restart: always
      image: php:7.1-alpine
      command: php -S 0.0.0.0:8000 -t /app/public/
      ports:
        - "8000:8000"
      volumes:
        - .:/app

    composer:
      image: composer/composer:latest
      command: install --ignore-platform-reqs
      volumes:
        - .:/app